import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//components
import HeaderComponent from "./[component]/HeaderComp";
import Contents from "./[component]/ContentsComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col items-center md:max-lg:w-[1024px]  sm:max-md:w-[768px] ">
          {/* 헤더 영역  */}
          <HeaderComponent />
          {/* 컨텐츠 영역  */}
          <Contents>{children}</Contents>
        </div>
      </body>
    </html>
  );
}
